### ISSUE TITLE
[FEAT] iOS 3차 과제 - TableView와 CollectionView

### ISSUE THREAD

**Issue by EunHee-Jeong** [29th-WE-SOPT-iOS-Part/JungEunHee#10]
## 📌  Feature Issue
3주차 과제는 TableView와 CollectionView를 활용하여

Youtube 홈 화면을 구성해보는 것입니다!

## 📝  To-do
▶️ UI 구성하기
- [x]  TableView 구성하기
- [x]  CollectionView 구성하기
- [x]  상단바 AutoLayout 설정하기

▶️ Cell 만들기
- [x]  TableViewCell 생성, 등록 및 호출하기
- [x]  CollectionViewCell 생성, 등록 및 호출하기
