### ISSUE TITLE
[FEAT] iOS 3차 과제 - 도전과제

### ISSUE THREAD

**Issue by EunHee-Jeong** [29th-WE-SOPT-iOS-Part/JungEunHee#12]
## 📌  Feature Issue
3주차 과제는 TableView와 CollectionView를 활용하여

Youtube 홈 화면을 구성해보는 것입니다!

## 📝  To-do

🔥 도전과제

- [x]  태그 영역 UI 구성
- [x] AutoLayout 잡기
- [x] CategoryCell 생성, 등록하기
- [x]  text 길이에 따라 Cell 크기 다르게 구현하기
