### ISSUE TITLE
[FEAT] iOS 7차 과제 - 데이터 연결 심화, UIGestureRecognizer

### ISSUE THREAD

**Issue by EunHee-Jeong** [29th-WE-SOPT-iOS-Part/JungEunHee#17]
## 📌  Feature Issue

썸네일 이미지를 tap 했을 때의 화면 전환과 데이터 전달

## 📝  To-do

- [x] imageView에 tap gesture recognizer 연결하기
- [x] present 화면 전환과 데이터 전달 (imageView, 제목, 조회수와 업로드 시간)
- [x] 버튼 눌렀을 때 이전 화면으로 dismiss
